### PR TITLE
there should be at least one file argument

### PR DESCRIPTION
**Pull request by murinicanor**
if there is no argument given, mat exits with no output and returns 0. if i understand correctly, mat needs at least one file argument. with this tiny patch it shows usage, if no file argument given and returns 2 ;)

### CODE REVIEW

**Comment by jvoisin** [comment]
What about showing the help by default then?

**Comment by jvoisin** [comment]
(I knew it was a great idea to not fix this minor annoyance to get contributions ;)

**Comment by murinicanor** [comment]
according to https://groups.google.com/forum/#!topic/argparse-users/LazV_tEQvQw one has to override the error() function of the argumentparser. did this in 8bb867a

**Comment by jvoisin** [comment]
Instantiating a whole class for this is overkill in my opinion: [this]( aa32b3dd050017d5876a924dd8ffb038285dc465 ) is how I did it instead.

**Comment by murinicanor** [comment]
well, imo argparse (either with a class or without, using default behaviour) does a lot of useful stuff. for instance, if you now call
```
mat -c
```
it exits with 0 and gives no hint that there was a problem...

**Comment by jvoisin** [comment]
Arg, indeed, this is an issue :<
Maybe I should have used your implementation instead :/

**Comment by jvoisin** [comment]
But on the other hand, `mat -l` isn't working with your solution ;)

**Comment by murinicanor** [comment]
ah, i see. now i understand why there was a * in the first place ;)

**Comment by murinicanor** [comment]
hi, i've deleted my branch and recreated it with a refinement of the argument handling if condition https://github.com/murinicanor/MAT/commit/7983af23b795eecea729791a113fc7a0565d3e51. now it should work as expected ;)

**Comment by jvoisin** [comment]
And you rebased on master ♥
I'll take a look at it right after my meeting, feel free to issue a PR :)

**Comment by murinicanor** [comment]
> And you rebased on master ♥
well... i tried to and failed. thats why i deleted and recreated the branch ;)
> I'll take a look at it right after my meeting, feel free to issue a PR :)
done.

**Pull request closed without merging**
