### PR TITLE
Correct desktop file

### PR DESCRIPTION
**Pull request by jubalh**
The keywords section should end with a semicolon.

### CODE REVIEW

**Comment by jubalh** [comment]
Oh, @jvoisin you should have pulled in the change form my branch :) this way it would have been clear who contributed it.
Anyways, the changed was pull in with commit beeb5f3f2c43823f51a80c9245af74708c84daa0.

**Comment by jvoisin** [comment]
I don't like github much, I prefer dealing with emails.
Feel free to send patches created with `git format-patch` if you want your name in the author field next time ;)

**Comment by jubalh** [comment]
Actually I sent you this patch with `git format-patch` initially ;) Then I saw that you use GitHub and did a PR here too. In either case the authorship of the patch should have been correct. But it seems like it is not.

**Comment by jvoisin** [comment]
Ouch. My bad then!
Sorry about this :/

**Pull request closed without merging**
